# Generated by Django 5.2.5 on 2025-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='smartKart/static/images/avatars/default_user.png', upload_to='userprofile'),
        ),
    ]
