# Generated by Django 5.2.5 on 2025-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/userprofile/default_user.png', upload_to='userprofile'),
        ),
    ]
