# Generated by Django 5.2.5 on 2025-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproduct_color_remove_orderproduct_size'),
        ('stores', '0002_varition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='varition',
            field=models.ManyToManyField(blank=True, to='stores.varition'),
        ),
    ]
